### ISSUE TITLE
Schematic diagram and PCB can't open.

### ISSUE THREAD

**Issue by xuekai1024** [GliderWinchItems/BMS#1]
Which software can I use to open the schematic diagram and PCB?

**Comment by xuekai1024** [comment]
cadence and AD both can't open it

**Comment by deh** [comment]
The schematic (.sch) and pcb layout (.brd) were generated by eagle. Autodesk now owns eagle. A free version can be downloaded--
https://www.autodesk.com/products/eagle/free-download
The files were generated with a paid version 4.2, but can be opened by all the later eagle versions. The pcb size is larger than the early free versions so changes cannot be made, but the latest version (v9) is based on area and the pcb falls within the limit.

**Comment by xuekai1024** [comment]
> The schematic (.sch) and pcb layout (.brd) were generated by eagle. Autodesk now owns eagle. A free version can be downloaded-- https://www.autodesk.com/products/eagle/free-download The files were generated with a paid version 4.2, but can be opened by all the later eagle versions. The pcb size is larger than the early free versions so changes cannot be made, but the latest version (v9) is based on area and the pcb falls within the limit.

Ｔｈａｎｋ　ｙｏｕ　ｓｏ　ｍｕｃｈ
